data:
    dataset: "S-UIEB"
    category: "type_3-7"
    image_size: 64
    channels: 3
    num_workers: 16
    data_dir: "/home/bachnguyen/Desktop/SLAM/underwater/UW-DDIM"
    conditional: True

tb_path: "/home/bachnguyen/Desktop/SLAM/underwater/UW-DDIM/logs"

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 8
    n_epochs: 10000
    snapshot_freq: 5000
    validation_freq: 10000

sampling:
    batch_size: 1
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
